version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: surgery-manager-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: